##### fleissner #####
#decypher
cipher="ŠMISUOŠAŠLSSUAMKIDAĖSSSUOUŽALOSSOAIMARPSGŠIPUPIAČLAEVOUASIISUULKŠUGBĖSRŽSIĘIŠLTĮAŲKESNRŠIUTŲPKŠAŲAITELŠAILUASŲAU"
./sabaton.exe -decypher -fleissner -frag "4;0001110010000000" "$cipher"
#brute
cipher="JAEITIKTOEGŽIUMIDKAĮIVGOVAĄAGKLOENRRTAKINIIISMLITSUVIOEJAKSIRIDŠEYIASPVDRJŽOUYINOAKIMĖDSAAUŽSGIDIASVSSOAPTANUPERIPŠDARIATATMŠOUO"
./sabaton.exe -decypher -fleissner -frag 4 "$cipher"